source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

# Define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'app_links'  # Add this line
end

target 'RunnerTests' do
  # Use dynamic frameworks
  use_frameworks!

  # Pods for RunnerTests
  # Add any test-specific pods here if needed
end